### ISSUE TITLE
Status check

### ISSUE THREAD

**Issue by thismatters** [KeLaiFu/Eurorack-Joystick#1]
This concept is pretty cool and I see that the original project you reference has disappeared. Have you been able to complete this module? What joystick did you settle on?

**Comment by KeLaiFu** [comment]
I made the PCBs but I could never get it working with the joystick I bought, which according to the original repo, should have been fine. I forgot about it and it's settled in a box somewhere with endless other abandonded ideas but I would hope I could probably figure out the issue with years of bumbling under my belt now. 
The original repo has moved to gitlabs, along with all analog output's great work. https://gitlab.com/rsholmes

**Comment by KeLaiFu** [comment]
btw, theres a few other JS modules which have public schematics, the most interesting one (imo) being the ouija from cctv: https://www.cctv.fm/product-page/ouija-eurorack-diy-kit?srsltid=AfmBOorCcE0AFDTMQhW-Uc4p-3rAa-znOjCxrKaESg6q4vmmIbbpP3pp

if i ever get time, i may attempt a kicad clone of this one.

**Comment by thismatters** [comment]
Dang! You've got a lot of modules under your belt!
